[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Security: Configure secrets scanning
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "DEPLOY_STEPS.md,SUPABASE_SETUP.md,deploy-edge-function.sh,*.md,*.sh"
  SECRETS_SCAN_ENABLED = "true"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200