[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "DEPLOY_STEPS.md,SUPABASE_SETUP.md,deploy-edge-function.sh,*.md,*.sh,README.md"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"
  SECRETS_SCAN_ENABLED = "true"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200